name: CD
on:
  push:
    branches: [ main ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Connect to ssh and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/cekwt/public_html/ &&
            git checkout main &&
            git reset --h &&
            #git clean -fd &&
            git pull &&
            rm -rf error_log &&
            #composer update &&
            #composer dump-autoload &&
            #php artisan migrate:fresh --seed --force &&
            php artisan migrate --force &&
            php artisan scribe:generate &&
            #php artisan passport:install &&
            php artisan optimize:clear &&
            php artisan cache:clear &&
            #php artisan config:clear &&
            php artisan view:clear
